drop table if exists CORVEICULO;
drop table if exists CONTACTO;
drop table if exists CONDHABILITADO;
drop table if exists CLIENTEVIAGEM;
drop table if exists VIAGEM cascade;
drop table if exists PERIODOACTIVO;
drop table if exists VEICULO;
drop table if exists TIPOVEICULO;
drop table if exists PROPRIETARIO;
drop table if exists CONDUTOR;
drop table if exists PESSOA;